# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: https://fadianchang.github.io
date_format: "ordinal"
title: Welkin
subtitle: "深知变美的路 有些曲折"
description: "speech synthesis/machine learning @ aslp, nwpu, Xi'an, ShannXi, China"
keywords: Welkin, GeMiniWelkin, Singng synthesis
timezone: Asia/Xi’an
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Heyang Xue
organization: 
organization_url: https://fadianchang.github.io
github_username: fadianchang

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: https://github.com/fadianchang/fadianchang.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: WelkinYang
    repo: Welkin
    clientID: 3845f377dfe8d3909639
    clientSecret: b7521f9fb6d44ed610ae16348fc8079d36eda413
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
